monitor.alsa.rules = []
stream.rules = [
  {
    matches = [
      { application.process.binary = "virt-viewer" }
      { application.process.binary = "remote-viewer" }
      { application.process.binary = "virt-manager" }
    ]
    actions = {
      update-props = {
        target.object = "SPplusVM"
        node.autoconnect = true
      }
    }
  }
]
